apiVersion: v1
kind: Secret
metadata:
  name: neuralseek-secrets
  namespace: neuralseek
type: Opaque
data:
  redis-master-password: bnNJbmdlc3RDb250cm9sUmVkaXM=
  redis-password: bnNJbmdlc3RDb250cm9sUmVkaXM=
  neo4j-password: ZGlhbG9nSW5nZXN0Q29udHJvbA==