apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neuralseek-db-pvc
  namespace: neuralseek
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi